const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const path=require("node:path");
const doc=require("../.test-build/fake-chat/document.js");const presets=require("../.test-build/fake-chat/presets.js");const persistence=require("../.test-build/fake-chat/persistence.js");

test("new document is versioned and has two editable people",()=>{const value=doc.newDocument();assert.equal(value.version,1);assert.equal(value.participants.A.id,"A");assert.equal(value.participants.B.id,"B")});
test("all eight presets switch without changing messages",()=>{let value=doc.newDocument();const count=value.messages.length;for(const preset of presets.CHAT_PRESETS){value=doc.switchPreset(value,preset.id);assert.equal(value.preset,preset.id);assert.equal(value.messages.length,count)}assert.equal(presets.CHAT_PRESETS.length,8)});
test("avatar fallback produces clean initials",()=>{assert.equal(doc.avatarInitials("Ada Lovelace"),"AL");assert.equal(doc.avatarInitials(""),"?")});
test("participant fields and data image survive normalization",()=>{const value=doc.newDocument();value.participants.A={...value.participants.A,name:"Amina Noor",username:"@amina",avatar:"data:image/png;base64,AA"};const loaded=doc.normaliseDocument(JSON.parse(JSON.stringify(value)));assert.equal(loaded.participants.A.name,"Amina Noor");assert.match(loaded.participants.A.avatar,/^data:image/) });
test("text supports multiline and long wrapping content",()=>{const text="first line\n"+"long ".repeat(300);const message=doc.newMessage("A",text);assert.equal(message.content,text)});
test("messages edit, duplicate, reorder and switch sender",()=>{let value=doc.documentFromTemplate("funny");const first=value.messages[0];value=doc.updateMessage(value,{...first,sender:"A",content:"edited"});assert.equal(value.messages[0].sender,"A");value=doc.duplicateMessage(value,first.id);assert.equal(value.messages.length,4);const copy=value.messages[1];assert.notEqual(copy.id,first.id);value=doc.moveMessage(value,copy.id,1);assert.equal(value.messages[2].id,copy.id)});
test("deleting a reply target clears the relation",()=>{let value=doc.newDocument();const target=value.messages[0];value.messages[1]={...value.messages[1],replyTo:target.id};value=doc.deleteMessage(value,target.id);assert.equal(value.messages[0].replyTo,null)});
test("every V1 media/event type, reactions and read state normalize",()=>{const types=["image","voice","video","sticker","location","missed_call","audio_call","video_call","system"];const value=doc.newDocument();value.messages=types.map((type,index)=>({...doc.newMessage(index%2?"A":"B","body",type),media:"data:image/png;base64,AA",reaction:"fire",seen:true,timestamp:"11:11"}));const loaded=doc.normaliseDocument(value);assert.deepEqual(loaded.messages.map(x=>x.type),types);assert.ok(loaded.messages.every(x=>x.reaction==="fire"&&x.seen&&x.timestamp==="11:11"))});
test("display realism and dark typing settings survive loading",()=>{const value=doc.newDocument();value.appearance.mode="dark";value.display.typing="B";value.display.statusBar=false;value.device.battery=150;const loaded=doc.normaliseDocument(value);assert.equal(loaded.appearance.mode,"dark");assert.equal(loaded.display.typing,"B");assert.equal(loaded.display.statusBar,false);assert.equal(loaded.device.battery,100)});
test("one hundred messages normalize with stable ids",()=>{const value=doc.newDocument();value.messages=Array.from({length:100},(_,i)=>doc.newMessage(i%2?"A":"B",`Message ${i}`));const loaded=doc.normaliseDocument(value);assert.equal(loaded.messages.length,100);assert.equal(new Set(loaded.messages.map(x=>x.id)).size,100)});
test("templates cover the requested starter set",()=>{assert.deepEqual(doc.TEMPLATE_NAMES,["blank","dating","funny","argument","business","support"])});
test("autosave helper debounces rapid edits",async()=>{let calls=0;const save=persistence.debounce(()=>calls++,20);save();save();save();await new Promise(r=>setTimeout(r,45));assert.equal(calls,1)});
test("route, navigation, export and migration are wired safely",()=>{const root=path.resolve(__dirname,"..");const read=p=>fs.readFileSync(path.join(root,p),"utf8");assert.match(read("app/dashboard/fake-chat/page.tsx"),/FakeChatStudio/);assert.match(read("components/Sidebar.tsx"),/dashboard\/fake-chat/);const exporter=read("lib/fake-chat/export.ts");assert.match(exporter,/cloneNode\(true\)/);assert.match(exporter,/toBlob/);assert.match(exporter,/scrollHeight/);assert.ok(!/editor|toolbarActions/.test(exporter));const sql=fs.readFileSync(path.resolve(root,"../supabase/migrations/20260911000000_create_fake_chat_projects.sql"),"utf8");assert.match(sql,/enable row level security/);assert.equal((sql.match(/create policy/g)||[]).length,4);assert.match(sql,/auth\.uid\(\).*user_id/)});
test("existing dashboard product routes remain present",()=>{const root=path.resolve(__dirname,"../app/dashboard");for(const route of ["football","story/horror","story/true","animated","quotes","clipping","analyzer"]){assert.ok(fs.existsSync(path.join(root,route,"page.tsx")),route)}});
