import {createClient,requireUser} from "@/lib/supabase/server";
import {AssetRepository,TaskRepository,toReelsHttpError} from "@/lib/vrf";
import {mediaImportPlan,parseVideoUrl} from "@/lib/vrf-ingest";
import {PoliceChaseRepository} from "@/lib/police-chase-repository";

export const dynamic="force-dynamic";
const lengths=new Set([15,30,45,60,90]);
function cleanSource(raw:Record<string,unknown>){return {title:String(raw.title??"").trim().slice(0,180),source_agency:String(raw.sourceAgency??"").trim().slice(0,120),original_source_url:String(raw.originalSourceUrl??"").trim().slice(0,500),footage_date:String(raw.footageDate??"").trim().slice(0,40),location:String(raw.location??"").trim().slice(0,120),reuse_basis:"owned_or_permitted",attribution_requirement:String(raw.attributionRequirement??"").trim().slice(0,300),verification_status:"user_attested",notes:String(raw.notes??"").trim().slice(0,500)}}
function publicTask(task:any){if(!task)return null;const clips=(Array.isArray(task.result?.clips)?task.result.clips:[]).map((item:any)=>{const {path:_path,error:_error,...safe}=item??{};return safe});return {...task,result:{...task.result,clips}}}
export async function GET(request:Request){try{await requireUser();const repo=new PoliceChaseRepository(await createClient());const id=new URL(request.url).searchParams.get("task");return Response.json({projects:id?[publicTask(await repo.get(id))]:(await repo.list()).map(publicTask)})}catch(err){const {status,message}=toReelsHttpError(err);return Response.json({error:message,projects:[]},{status})}}
export async function POST(request:Request){try{const user=await requireUser();const body=await request.json() as Record<string,unknown>;if(body.ownsOrPermitted!==true)return Response.json({error:"Confirm you own this footage or have permission to reuse it."},{status:400});const raw=(body.options??{}) as Record<string,unknown>;const target=Number(raw.targetSeconds);const count=Math.max(1,Math.min(5,Number(raw.count)||1));const caption=["auto","en","ar","none"].includes(String(raw.captionLanguage))?String(raw.captionLanguage):"auto";const ctaMode=["auto","custom","off"].includes(String(raw.ctaMode))?String(raw.ctaMode):"auto";const ctaText=String(raw.ctaText??"").trim().slice(0,90);if(ctaMode==="custom"&&!ctaText)return Response.json({error:"Enter the custom follow message."},{status:400});const supabase=await createClient();const assets=new AssetRepository(supabase);const tasks=new TaskRepository(supabase);let assetId=String(body.assetId??"").trim();const sourceUrl=String(body.sourceUrl??"").trim();if(sourceUrl){const parsed=parseVideoUrl(sourceUrl);const {data,error}=await supabase.from("vrf_accounts").select("platform, revoked_at").is("revoked_at",null);if(error)throw new Error(error.message);const connected=(data??[]).map(row=>String(row.platform));const plan=mediaImportPlan(parsed,connected);if(!plan.canFetchMedia)return Response.json({error:plan.reason},{status:409});const asset=await assets.createFromUrl(user.id,{url:sourceUrl,ownsOrPermitted:true,connectedPlatforms:connected});assetId=asset.id}if(!assetId)return Response.json({error:"Paste an authorized source link or upload a video."},{status:400});const asset=await assets.get(assetId);if(!String(asset.storage_path??"").trim())return Response.json({error:"This source does not include a processable video file. Upload the authorized original."},{status:409});const source=cleanSource((body.sourceMetadata??{}) as Record<string,unknown>);const task=await tasks.create(user.id,"process",{product:"police_chase",asset_id:asset.id,platform:"tiktok",police_chase:{target_seconds:lengths.has(target)?target:30,count,caption_language:caption,cta_mode:ctaMode,cta_text:ctaText,cta_placement:raw.ctaPlacement==="persistent"?"persistent":"end",source_metadata:source,retry_moment:body.retryMoment??null}});return Response.json({task:publicTask(task)},{status:201})}catch(err){const {status,message}=toReelsHttpError(err);return Response.json({error:message},{status})}}
