"""Sound: recorded from Freesound, generated by ElevenLabs.

Two sources with opposite strengths, which is why both are here.

  Freesound   Real recordings, and the right answer for ambience -- a room
              tone or a rain bed that was actually recorded sounds like a
              place, and a generated one rarely does. Licences vary per sound
              and several of them cannot be used in a monetisable video, so
              every result is checked against its own licence rather than
              trusted because a search filter was passed.
  ElevenLabs  Generated to a description, and the right answer for a specific
              one-off cue that no catalogue happens to hold -- "a chair
              scraping back on a stone floor, once, close" is a generation
              prompt, not a search query.

Narration is not here. It stays on Gemini TTS, untouched.

Licences
--------
Freesound reports a licence *URL*, not a name -- `.../publicdomain/zero/1.0/`
rather than "CC0". `licence_name_from_url` maps it back to the vocabulary the
rest of this codebase uses, so the same `is_reusable_licence` gate that guards
footage and Commons stills also guards sound. CC0 and CC-BY are accepted;
non-commercial and no-derivatives are rejected, and CC-BY carries a credit
obligation that is recorded with the file.

Generated audio has no upstream licence and no author to credit. It is
recorded as generated so nothing downstream mistakes it for a recording.
"""

from __future__ import annotations

import logging
import re

import httpx

from core.footage_discovery import is_reusable_licence
from core.providers.base import (
    Availability,
    MediaItem,
    MediaKind,
    ProviderStatus,
    RateLimiter,
    credential,
    with_retries,
)

logger = logging.getLogger("video_factory")


# ---------------------------------------------------------------------------
# Licence URLs
# ---------------------------------------------------------------------------

#: Freesound's licence URLs, mapped to the names used everywhere else here.
_LICENCE_URLS = (
    (re.compile(r"publicdomain/zero", re.I), "CC0"),
    (re.compile(r"publicdomain/mark", re.I), "Public Domain"),
    (re.compile(r"licenses/by-nc-sa/", re.I), "CC BY-NC-SA"),
    (re.compile(r"licenses/by-nc-nd/", re.I), "CC BY-NC-ND"),
    (re.compile(r"licenses/by-nc/", re.I), "CC BY-NC"),
    (re.compile(r"licenses/by-nd/", re.I), "CC BY-ND"),
    (re.compile(r"licenses/by-sa/", re.I), "CC BY-SA"),
    (re.compile(r"licenses/by/", re.I), "CC BY"),
    (re.compile(r"samplingplus", re.I), "Sampling+"),
)


def licence_name_from_url(value: str) -> str:
    """A licence name from Freesound's URL, or the input if already a name.

    Order matters: `by-nc-sa` has to be recognised before `by-sa` and `by`,
    or a non-commercial sound is mislabelled as one we may use.
    """
    text = str(value or "").strip()
    if not text:
        return ""
    if "://" not in text:
        return text
    for pattern, name in _LICENCE_URLS:
        if pattern.search(text):
            return name
    return text


# ---------------------------------------------------------------------------
# Freesound
# ---------------------------------------------------------------------------

class FreesoundProvider:
    """Recorded ambience and sound effects.

    Only previews are used. Freesound's original-quality download requires
    OAuth2, which this deployment does not hold; the high-quality preview is a
    128kbps MP3, which is well beyond what an ambience bed sitting under
    narration needs.
    """

    name = "freesound"
    SEARCH_URL = "https://freesound.org/apiv2/search/text/"
    FIELDS = "id,name,license,username,url,previews,duration,tags"

    #: Passed to the API to narrow the result set. The per-result check below
    #: is the one that actually decides -- a filter is a request, not a
    #: guarantee, and Freesound adds licence variants over time.
    LICENCE_FILTER = 'license:("Creative Commons 0" OR "Attribution")'

    def __init__(self, api_key: str | None = None) -> None:
        self._key = api_key if api_key is not None else credential("freesound_api_key")
        self._limiter = RateLimiter(concurrency=2, min_interval=0.4)

    def status(self) -> ProviderStatus:
        if not self._key:
            return ProviderStatus(
                self.name, Availability.NEEDS_CREDENTIALS,
                "Set FREESOUND_API_KEY (free from freesound.org/apiv2/apply).",
            )
        return ProviderStatus(self.name, Availability.READY)

    async def search(
        self,
        query: str,
        *,
        client: httpx.AsyncClient,
        limit: int = 10,
        min_duration: float = 0.0,
        max_duration: float = 0.0,
        **_,
    ) -> list[MediaItem]:
        if not self.status().usable or not query.strip():
            return []

        filters = [self.LICENCE_FILTER]
        if min_duration or max_duration:
            low = f"{max(0.0, min_duration):.1f}"
            high = f"{max_duration:.1f}" if max_duration else "*"
            filters.append(f"duration:[{low} TO {high}]")

        params = {
            "query": query,
            "filter": " ".join(filters),
            "fields": self.FIELDS,
            "page_size": max(1, min(limit, 50)),
            "sort": "score",
        }

        async def call():
            response = await client.get(
                self.SEARCH_URL,
                params=params,
                # In a header rather than a `token` query parameter: an API
                # key in a URL ends up in logs and referrers.
                headers={"Authorization": f"Token {self._key}"},
            )
            response.raise_for_status()
            return response.json() or {}

        async with self._limiter:
            body = await with_retries(call, provider=self.name)

        items: list[MediaItem] = []
        rejected = 0

        for hit in body.get("results") or []:
            licence = licence_name_from_url(str(hit.get("license") or ""))
            if not is_reusable_licence(licence):
                rejected += 1
                continue

            previews = hit.get("previews") or {}
            url = str(
                previews.get("preview-hq-mp3")
                or previews.get("preview-hq-ogg")
                or previews.get("preview-lq-mp3")
                or ""
            )
            if not url:
                continue

            items.append(MediaItem(
                provider=self.name,
                provider_id=str(hit.get("id") or ""),
                kind=MediaKind.AUDIO,
                url=url,
                source_page=str(hit.get("url") or ""),
                licence=licence,
                attribution=str(hit.get("username") or ""),
                title=str(hit.get("name") or ""),
                duration_seconds=float(hit.get("duration") or 0.0),
                query=query,
            ))

        if rejected:
            logger.info(
                f"[freesound] {len(items)} usable, {rejected} rejected on licence"
            )
        return items


# ---------------------------------------------------------------------------
# ElevenLabs sound effects
# ---------------------------------------------------------------------------

class ElevenLabsSfxProvider:
    """Sound effects generated from a description.

    Text-to-sound-effects only. Narration is Gemini TTS and stays that way, so
    nothing here touches a voice.

    Generation costs credits per call, so the caller is expected to ask for a
    cue it could not find a recording of, rather than as a first resort.
    """

    name = "elevenlabs_sfx"
    URL = "https://api.elevenlabs.io/v1/sound-generation"
    MODEL = "eleven_text_to_sound_v2"
    #: The API's own bounds.
    MIN_SECONDS = 0.5
    MAX_SECONDS = 30.0

    def __init__(self, api_key: str | None = None) -> None:
        self._key = api_key if api_key is not None else credential("elevenlabs_api_key")
        self._limiter = RateLimiter(concurrency=1, min_interval=0.5)

    def status(self) -> ProviderStatus:
        if not self._key:
            return ProviderStatus(
                self.name, Availability.NEEDS_CREDENTIALS,
                "Set ELEVENLABS_API_KEY.",
            )
        if not self._key.startswith("sk_"):
            # The dashboard shows a key *id* next to each key, and it is easy
            # to copy that instead. It authenticates as nothing, and the error
            # it returns is not obviously about the wrong value being copied.
            return ProviderStatus(
                self.name, Availability.NEEDS_CREDENTIALS,
                "ELEVENLABS_API_KEY looks like an API key ID rather than the "
                "key itself. The key starts with 'sk_' and is shown only when "
                "it is created or rotated.",
            )
        return ProviderStatus(self.name, Availability.READY)

    async def generate(
        self,
        description: str,
        *,
        client: httpx.AsyncClient,
        duration_seconds: float | None = None,
        loop: bool = False,
        prompt_influence: float = 0.35,
    ) -> bytes:
        """MP3 bytes for one cue. Raises on refusal rather than returning silence."""
        if not self.status().usable:
            raise RuntimeError(self.status().reason)
        if not description.strip():
            raise ValueError("a sound effect needs a description")

        payload: dict = {
            "text": description.strip(),
            "model_id": self.MODEL,
            "prompt_influence": max(0.0, min(1.0, prompt_influence)),
            # A looping bed has to end where it starts, or the seam is audible
            # every time it wraps.
            "loop": bool(loop),
        }
        if duration_seconds is not None:
            payload["duration_seconds"] = max(
                self.MIN_SECONDS, min(self.MAX_SECONDS, float(duration_seconds)))

        async def call():
            response = await client.post(
                self.URL,
                params={"output_format": "mp3_44100_128"},
                headers={"xi-api-key": self._key, "Content-Type": "application/json"},
                json=payload,
            )
            response.raise_for_status()
            return response.content

        async with self._limiter:
            return await with_retries(call, provider=self.name)

    def describe(self, description: str, *, loop: bool) -> dict:
        """The provenance record for a generated cue.

        Deliberately not shaped like a recording: there is no source page and
        no author, and `licence` says the sound was generated, so nothing
        downstream can present it as something that was recorded somewhere.
        """
        return {
            "platform": self.name,
            "url": "",
            "source_page": "",
            "licence": "generated (ElevenLabs sound effects)",
            "attribution": "",
            "width": 0,
            "height": 0,
            "prompt": description,
            "loop": bool(loop),
        }
