"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {CAPTION_LANGUAGES,CHASE_COUNTS,CHASE_LENGTHS,CTA_MODES,defaultChaseOptions,defaultChaseSource,reuseLabel,safeChaseError,type ChaseClip,type ChaseOptions,type ChaseSource} from "@/lib/police-chase";

type Asset={id:string;title:string;duration_seconds:number|null;storage_path:string};
type Task={id:string;status:"queued"|"running"|"done"|"failed";payload:Record<string,any>;result:Record<string,any>;error:string;created_at:string};
const clock=(n:number)=>`${Math.floor(n/60)}:${String(Math.round(n%60)).padStart(2,"0")}`;
export function PoliceChaseStudio({initialAssets,initialProjects}:{initialAssets:Asset[];initialProjects:Task[]}){
 const first=initialProjects[0]??null;const [assets,setAssets]=useState(initialAssets);const [task,setTask]=useState<Task|null>(first);const [options,setOptions]=useState<ChaseOptions>(()=>({...defaultChaseOptions(),...(first?.payload?.police_chase??{})}));const [source,setSource]=useState<ChaseSource>(()=>({...defaultChaseSource(),...(first?.payload?.police_chase?.source_metadata??{})}));const [assetId,setAssetId]=useState(String(first?.payload?.asset_id??""));const [url,setUrl]=useState("");const [authorized,setAuthorized]=useState(false);const [busy,setBusy]=useState(false);const [uploading,setUploading]=useState(false);const [progress,setProgress]=useState(0);const [error,setError]=useState("");const [media,setMedia]=useState<Record<string,string>>({});const [showDetails,setShowDetails]=useState(false);const fileRef=useRef<HTMLInputElement>(null);
 const running=task?.status==="queued"||task?.status==="running";const clips=(Array.isArray(task?.result?.clips)?task?.result?.clips:[]) as ChaseClip[];
 const poll=useCallback(async()=>{if(!task?.id)return;try{const r=await fetch(`/api/police-chase?task=${encodeURIComponent(task.id)}`,{cache:"no-store"});const b=await r.json();if(r.ok&&b.projects?.[0])setTask(b.projects[0])}catch{}},[task?.id]);
 useEffect(()=>{if(!running)return;const timer=setInterval(poll,3000);return()=>clearInterval(timer)},[running,poll]);
 useEffect(()=>{if(task?.status!=="done")return;for(const clip of clips.filter(c=>c.status!=="failed")){if(media[clip.id])continue;fetch(`/api/reels/clips/media?task=${encodeURIComponent(task.id)}&clip=${encodeURIComponent(clip.id)}`).then(r=>r.json()).then(b=>{if(b.url)setMedia(v=>({...v,[clip.id]:b.url}))}).catch(()=>{})}},[task?.status,task?.id,clips.length,media]);
 async function chooseFile(file:File|null){if(!file)return;setUploading(true);setError("");setProgress(1);try{const sign=await fetch("/api/reels/clips/upload",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"sign",filename:file.name,contentType:file.type,size:file.size})});const s=await sign.json();if(!sign.ok)throw new Error(s.error);await put(s.uploadUrl,file,s.headers??{},setProgress);const saved=await fetch("/api/reels/clips/upload",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"commit",objectPath:s.objectPath,title:file.name.replace(/\.[^.]+$/,""),ownsOrPermitted:true})});const b=await saved.json();if(!saved.ok)throw new Error(b.error);setAssets(v=>[b.asset,...v.filter(x=>x.id!==b.asset.id)]);setAssetId(b.asset.id);setSource(v=>({...v,title:v.title||b.asset.title}));setProgress(100)}catch(e){setError(safeChaseError((e as Error).message))}finally{setUploading(false)}}
 async function create(retryMoment?:unknown){if((!assetId&&!url.trim())||!authorized)return;setBusy(true);setError("");try{const r=await fetch("/api/police-chase",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({assetId:assetId||undefined,sourceUrl:assetId?undefined:url,ownsOrPermitted:true,options,sourceMetadata:source,retryMoment})});const b=await r.json();if(!r.ok)throw new Error(b.error);setTask(b.task);setMedia({})}catch(e){setError(safeChaseError((e as Error).message))}finally{setBusy(false)}}
 function open(project:Task){setTask(project);setAssetId(String(project.payload?.asset_id??""));setOptions({...defaultChaseOptions(),...(project.payload?.police_chase??{})});setSource({...defaultChaseSource(),...(project.payload?.police_chase?.source_metadata??{})});setAuthorized(true);setMedia({})}
 return <div className="pc-studio" data-surface="police-chase">
  <header className="pc-hero"><div><span>POLICE CHASE STUDIO</span><h1>Find the moment the chase turns.</h1><p>Prepare authorized bodycam and dashcam footage for vertical social video—without guessing about reuse rights.</p></div><select aria-label="Saved Police Chase projects" value={task?.id??""} onChange={e=>{const p=initialProjects.find(x=>x.id===e.target.value);if(p)open(p)}}><option value="">New project</option>{initialProjects.map(p=><option key={p.id} value={p.id}>{String(p.payload?.police_chase?.source_metadata?.title||"Saved chase")}</option>)}</select></header>
  {error&&<p className="notice notice-error" role="alert">{error}</p>}
  {!running&&task?.status!=="done"&&<div className="pc-workspace"><main className="pc-source"><div className="pc-section-head"><span>01 · SOURCE</span><h2>Bring authorized footage</h2></div><div className="pc-url"><span>↗</span><input value={url} onChange={e=>{setUrl(e.target.value);if(e.target.value)setAssetId("")}} placeholder="Paste an authorized source URL"/><button onClick={()=>fileRef.current?.click()} type="button">Upload video</button></div><input ref={fileRef} hidden type="file" accept="video/mp4,video/quicktime,video/webm,video/x-matroska,.mp4,.mov,.webm,.mkv" onChange={e=>chooseFile(e.target.files?.[0]??null)}/>{uploading&&<div className="pc-upload"><i style={{width:`${progress}%`}}/><span>Uploading {progress}%</span></div>}{assets.length>0&&<div className="pc-assets">{assets.slice(0,6).map(a=><button type="button" className={assetId===a.id?"is-on":""} key={a.id} onClick={()=>{setAssetId(a.id);setUrl("");setSource(v=>({...v,title:v.title||a.title}))}}><b>{a.title}</b><small>{a.duration_seconds?clock(a.duration_seconds):"Uploaded source"}</small></button>)}</div>}
   <div className="pc-rights"><div className="pc-beacon"><i/><div><b>{reuseLabel(source.verificationStatus)}</b><span>Uploaded footage is processed only after your authorization.</span></div></div><div className="pc-meta-grid"><label>Footage title<input value={source.title} onChange={e=>setSource({...source,title:e.target.value})}/></label><label>Source agency<input value={source.sourceAgency} onChange={e=>setSource({...source,sourceAgency:e.target.value})}/></label><label>Original source URL<input value={source.originalSourceUrl} onChange={e=>setSource({...source,originalSourceUrl:e.target.value})}/></label><label>Location<input value={source.location} onChange={e=>setSource({...source,location:e.target.value})}/></label><label>Footage date<input type="date" value={source.footageDate} onChange={e=>setSource({...source,footageDate:e.target.value})}/></label><label>Attribution / license note<input value={source.attributionRequirement} onChange={e=>setSource({...source,attributionRequirement:e.target.value})}/></label></div><button className="pc-details" type="button" onClick={()=>setShowDetails(!showDetails)}>{showDetails?"Hide":"Add"} restrictions and notes</button>{showDetails&&<textarea value={source.notes} onChange={e=>setSource({...source,notes:e.target.value})} placeholder="Restrictions, redactions, sensitive context…"/>}</div></main>
   <aside className="pc-settings"><div className="pc-section-head"><span>02 · CUT</span><h2>Clip settings</h2></div><label>Target length<div className="pc-pills">{CHASE_LENGTHS.map(n=><button type="button" className={options.targetSeconds===n?"is-on":""} onClick={()=>setOptions({...options,targetSeconds:n})} key={n}>{n}s</button>)}</div></label><label>Number of clips<div className="pc-pills">{CHASE_COUNTS.map(n=><button type="button" className={options.count===n?"is-on":""} onClick={()=>setOptions({...options,count:n})} key={n}>{n}</button>)}</div></label><label>Caption language<select value={options.captionLanguage} onChange={e=>setOptions({...options,captionLanguage:e.target.value})}>{CAPTION_LANGUAGES.map(x=><option value={x.id} key={x.id}>{x.label}</option>)}</select></label><label>Follow CTA<select value={options.ctaMode} onChange={e=>setOptions({...options,ctaMode:e.target.value})}>{CTA_MODES.map(x=><option value={x.id} key={x.id}>{x.label}</option>)}</select></label>{options.ctaMode==="custom"&&<label>CTA text<input maxLength={90} value={options.ctaText} onChange={e=>setOptions({...options,ctaText:e.target.value})}/></label>}{options.ctaMode!=="off"&&<label>CTA placement<select value={options.ctaPlacement} onChange={e=>setOptions({...options,ctaPlacement:e.target.value as "end"|"persistent"})}><option value="end">Final 2–3 seconds</option><option value="persistent">Persistent small CTA</option></select></label>}<div className="pc-output"><span>OUTPUT</span><b>9:16 vertical · Original audio</b></div><label className="pc-check"><input type="checkbox" checked={authorized} onChange={e=>setAuthorized(e.target.checked)}/>I own this footage or have permission to reuse it.</label><button className="pc-create" disabled={busy||uploading||(!assetId&&!url.trim())||!authorized} onClick={()=>create()} type="button">{busy?"Preparing…":"Create chase clips"}</button></aside></div>}
  {running&&<section className="pc-progress"><div className="pc-scan"/><span>ANALYZING FULL SOURCE</span><h2>Finding the strongest turning points…</h2><p>Pursuit, maneuvers, interactions, climax and resolution.</p></section>}
  {task?.status==="failed"&&<section className="pc-progress"><span>NEEDS ATTENTION</span><h2>This project needs attention.</h2><p>{safeChaseError(task.error)}</p><button className="btn-ghost" onClick={()=>setTask(null)}>Review source</button></section>}
  {task?.status==="done"&&<section className="pc-results"><div className="pc-results-head"><div><span>COMPLETE</span><h2>Prepared chase clips</h2></div><button className="btn-ghost" onClick={()=>setTask(null)}>New project</button></div><div className="pc-gallery">{clips.map(clip=><article key={clip.id} className={clip.status==="failed"?"is-failed":""}><div className="pc-video">{media[clip.id]?<video controls playsInline src={media[clip.id]}/>:<div>{clip.status==="failed"?"Needs attention":"Preparing preview…"}</div>}<b>{clip.viral_score}<small>SCORE</small></b></div><div className="pc-card-body"><span>{clip.reason}</span><h3>{clip.title}</h3><p>{clock(clip.start)}–{clock(clip.end)} · {clock(clip.duration)}</p><dl><div><dt>Rights</dt><dd>{reuseLabel(String(task.result?.source_metadata?.verification_status||"user_attested"))}</dd></div><div><dt>Captions</dt><dd>{clip.caption_status||"Original preserved"}</dd></div><div><dt>CTA</dt><dd>{clip.cta_text||"Off"}</dd></div></dl>{clip.status==="failed"?<button className="btn-ghost" onClick={()=>create(clip)}>Retry this clip</button>:<div className="pc-actions"><a className="btn-primary" href={media[clip.id]} download>Download MP4</a><button className="btn-ghost" onClick={()=>create(clip)}>Rerender</button></div>}</div></article>)}</div></section>}
 </div>
}
function put(url:string,file:File,headers:Record<string,string>,progress:(n:number)=>void){return new Promise<void>((resolve,reject)=>{const x=new XMLHttpRequest();x.open("PUT",url,true);Object.entries(headers).forEach(([k,v])=>x.setRequestHeader(k,v));x.upload.onprogress=e=>e.lengthComputable&&progress(Math.round(e.loaded/e.total*100));x.onload=()=>x.status>=200&&x.status<300?resolve():reject(new Error("Upload did not complete."));x.onerror=()=>reject(new Error("Upload was interrupted."));x.send(file)})}
