"use client";
import { useCallback,useEffect,useRef,useState } from "react";
import { CHAT_PRESETS,documentFromTemplate,newDocument,normaliseDocument,switchPreset,TEMPLATE_NAMES } from "@/lib/fake-chat/document";
import { exportChatPng,type ExportMode } from "@/lib/fake-chat/export";
import type { FakeChatDocument,FakeChatProject } from "@/lib/fake-chat/types";
import { MessageEditor } from "./MessageEditor";
import { ParticipantEditor,swapParticipants } from "./ParticipantEditor";
import { PhonePreview } from "./PhonePreview";
import styles from "./fake-chat.module.css";

type SaveState="Saved"|"Saving…"|"Unsaved changes";
export function FakeChatStudio({initialProjects}:{initialProjects:FakeChatProject[]}){
  const first=initialProjects[0]??null;const [doc,setDoc]=useState(()=>normaliseDocument(first?.document??newDocument()));const [projects,setProjects]=useState(initialProjects);const [projectId,setProjectId]=useState(first?.id??"");const [saveState,setSaveState]=useState<SaveState>(first?"Saved":"Unsaved changes");const [error,setError]=useState("");const [history,setHistory]=useState<FakeChatDocument[]>([]);const [future,setFuture]=useState<FakeChatDocument[]>([]);const previewRef=useRef<HTMLDivElement>(null);const saveTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
  const change=useCallback((next:FakeChatDocument)=>{setHistory((items)=>[...items.slice(-39),doc]);setFuture([]);setDoc(normaliseDocument(next));setSaveState("Unsaved changes")},[doc]);
  const undo=useCallback(()=>{const previous=history.at(-1);if(!previous)return;setFuture((items)=>[doc,...items]);setHistory((items)=>items.slice(0,-1));setDoc(previous);setSaveState("Unsaved changes")},[doc,history]);
  const redo=useCallback(()=>{const next=future[0];if(!next)return;setHistory((items)=>[...items,doc]);setFuture((items)=>items.slice(1));setDoc(next);setSaveState("Unsaved changes")},[doc,future]);

  const save=useCallback(async()=>{setSaveState("Saving…");setError("");try{const response=await fetch(projectId?`/api/fake-chat/projects/${projectId}`:"/api/fake-chat/projects",{method:projectId?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:doc.title,document:doc})});const body=await response.json();if(!response.ok)throw new Error(body.error);const project=body.project as FakeChatProject;setProjectId(project.id);setProjects((items)=>[project,...items.filter((item)=>item.id!==project.id)]);setSaveState("Saved")}catch{setSaveState("Unsaved changes");setError("We couldn't save this chat.")}},[doc,projectId]);
  useEffect(()=>{if(!projectId||saveState!=="Unsaved changes")return;if(saveTimer.current)clearTimeout(saveTimer.current);saveTimer.current=setTimeout(save,900);return()=>{if(saveTimer.current)clearTimeout(saveTimer.current)}},[projectId,save,saveState]);
  useEffect(()=>{const handler=(event:KeyboardEvent)=>{if(!(event.ctrlKey||event.metaKey)||event.key.toLowerCase()!=="z")return;event.preventDefault();event.shiftKey?redo():undo()};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler)},[redo,undo]);

  const exportImage=async(mode:ExportMode)=>{if(!previewRef.current)return;setError("");try{await exportChatPng(previewRef.current,mode,`${doc.title.replace(/[^a-z0-9]+/gi,"-").toLowerCase()||"fake-chat"}.png`)}catch{setError("We couldn't export the image. Try again.")}};
  const open=(project:FakeChatProject)=>{setProjectId(project.id);setDoc(normaliseDocument(project.document));setHistory([]);setFuture([]);setSaveState("Saved")};
  const fresh=()=>{setProjectId("");setDoc(newDocument());setHistory([]);setFuture([]);setSaveState("Unsaved changes")};
  const duplicateProject=()=>{setProjectId("");change({...doc,title:`${doc.title} copy`})};
  const remove=async()=>{if(!projectId||!confirm("Delete this saved chat? This cannot be undone."))return;try{const response=await fetch(`/api/fake-chat/projects/${projectId}`,{method:"DELETE"});if(!response.ok)throw new Error();setProjects((items)=>items.filter((item)=>item.id!==projectId));fresh()}catch{setError("We couldn't delete this chat.")}};
  const resetStyle=()=>change({...doc,appearance:newDocument().appearance,device:newDocument().device,display:newDocument().display});
  const background=(file:File|null)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>change({...doc,appearance:{...doc.appearance,backgroundImage:String(reader.result||"")}});reader.readAsDataURL(file)};

  return <div className={styles.studio}>
    <header className={styles.toolbar}><div><span>CREATIVE MOCKUP TOOL</span><h1>Fake Chat Studio</h1><p>Create chat mockups for storytelling, entertainment, and design.</p></div><div className={styles.toolbarActions}><button onClick={undo} disabled={!history.length} type="button">Undo</button><button onClick={redo} disabled={!future.length} type="button">Redo</button><button onClick={fresh} type="button">New chat</button><button className={styles.save} onClick={save} type="button">Save</button><small className={styles[saveState.replace(/\W/g,"").toLowerCase()]}>{saveState}</small></div></header>
    {error&&<p className={styles.error} role="alert">{error}</p>}
    <div className={styles.workspace}>
      <main className={styles.editor}>
        <section className={styles.panel}><div className={styles.panelTitle}><span>STYLE</span><h2>Choose the conversation</h2></div><div className={styles.presetGrid}>{CHAT_PRESETS.map((preset)=><button type="button" key={preset.id} className={doc.preset===preset.id?styles.selected:""} onClick={()=>change(switchPreset(doc,preset.id))}><i>{preset.mark}</i><span>{preset.name}</span></button>)}</div><div className={styles.templates}><label>Starter template<select defaultValue="" onChange={(e)=>{if(e.target.value)change(documentFromTemplate(e.target.value))}}><option value="" disabled>Choose a starting point</option>{TEMPLATE_NAMES.map((name)=><option key={name} value={name}>{name==="support"?"Customer Support":name[0].toUpperCase()+name.slice(1)}</option>)}</select></label></div></section>
        <section className={styles.panel}><div className={styles.panelTitle}><span>PEOPLE</span><h2>Participants</h2></div><div className={styles.people}><ParticipantEditor participant={doc.participants.A} onChange={(person)=>change({...doc,participants:{...doc.participants,A:person}})}/><ParticipantEditor participant={doc.participants.B} onChange={(person)=>change({...doc,participants:{...doc.participants,B:person}})}/></div><button className={styles.textButton} type="button" onClick={()=>change({...doc,participants:swapParticipants(doc.participants),messages:doc.messages.map((message)=>({...message,sender:message.sender==="A"?"B":"A"}))})}>⇄ Swap participants</button></section>
        <section className={styles.panel}><div className={styles.panelTitle}><span>CONVERSATION</span><h2>Messages</h2></div><MessageEditor doc={doc} onChange={change}/><button className={styles.dangerButton} type="button" onClick={()=>confirm("Clear every message?")&&change({...doc,messages:[]})}>Clear conversation</button></section>
        <section className={styles.panel}><div className={styles.panelTitle}><span>REALITY</span><h2>Display details</h2></div><div className={styles.settingsGrid}><label>Appearance<select value={doc.appearance.mode} onChange={(e)=>change({...doc,appearance:{...doc.appearance,mode:e.target.value as "light"|"dark"}})}><option value="light">Light</option><option value="dark">Dark</option></select></label><label>Phone frame<select value={doc.device.frame} onChange={(e)=>change({...doc,device:{...doc.device,frame:e.target.value as "iphone"|"android"|"none"}})}><option value="iphone">iPhone-style</option><option value="android">Android-style</option><option value="none">Screenshot only</option></select></label><label>Device time<input value={doc.device.time} onChange={(e)=>change({...doc,device:{...doc.device,time:e.target.value}})}/></label><label>Battery<input type="number" min="0" max="100" value={doc.device.battery} onChange={(e)=>change({...doc,device:{...doc.device,battery:Number(e.target.value)}})}/></label><label>Date label<input value={doc.display.dateLabel} onChange={(e)=>change({...doc,display:{...doc.display,dateLabel:e.target.value}})}/></label><label>Typing indicator<select value={doc.display.typing} onChange={(e)=>change({...doc,display:{...doc.display,typing:e.target.value as "A"|"B"|"off"}})}><option value="off">Off</option><option value="A">Person A typing</option><option value="B">Person B typing</option></select></label><label>Spacing<select value={doc.appearance.spacing} onChange={(e)=>change({...doc,appearance:{...doc.appearance,spacing:e.target.value as "normal"|"compact"}})}><option value="normal">Normal</option><option value="compact">Compact</option></select></label><label>Background color<input type="color" value={doc.appearance.backgroundColor} onChange={(e)=>change({...doc,appearance:{...doc.appearance,backgroundColor:e.target.value}})}/></label><label>Wallpaper<input type="file" accept="image/*" onChange={(e)=>background(e.target.files?.[0]??null)}/></label></div><div className={styles.toggles}>{([['statusBar','Status bar'],['timestamps','Timestamps'],['avatars','Avatars'],['readState','Delivered / seen'],['dateSeparators','Date divider'],['onlineStatus','Online status']] as const).map(([key,label])=><label key={key}><input type="checkbox" checked={doc.display[key]} onChange={(e)=>change({...doc,display:{...doc.display,[key]:e.target.checked}})}/>{label}</label>)}</div><button className={styles.textButton} type="button" onClick={resetStyle}>Reset style settings</button></section>
      </main>
      <aside className={styles.previewColumn}><div className={styles.previewSticky}><div className={styles.previewTop}><div><span>LIVE PREVIEW</span><input aria-label="Chat title" value={doc.title} onChange={(e)=>change({...doc,title:e.target.value})}/></div><select aria-label="Saved chats" value={projectId} onChange={(e)=>{const project=projects.find((item)=>item.id===e.target.value);if(project)open(project)}}><option value="">Unsaved chat</option>{projects.map((project)=><option key={project.id} value={project.id}>{project.title}</option>)}</select></div><PhonePreview ref={previewRef} doc={doc}/><div className={styles.exportBox}><button className={styles.primaryExport} type="button" onClick={()=>exportImage("screen")}>Download screenshot</button><button type="button" onClick={()=>exportImage("full")}>Full conversation</button><select aria-label="Export size" onChange={(e)=>e.target.value&&exportImage(e.target.value as ExportMode)} defaultValue=""><option value="" disabled>More export sizes</option><option value="story">1080 × 1920 Story</option><option value="native">Native chat width</option></select><div><button type="button" onClick={duplicateProject}>Duplicate project</button>{projectId&&<button type="button" className={styles.danger} onClick={remove}>Delete project</button>}</div></div></div></aside>
    </div>
  </div>
}
