"use client";
import React from "react";
import { deleteMessage, duplicateMessage, moveMessage, newMessage, updateMessage } from "@/lib/fake-chat/document";
import type { FakeChatDocument, MessageType, ParticipantId, Reaction } from "@/lib/fake-chat/types";
import styles from "./fake-chat.module.css";

const TYPES:[MessageType,string][]=[["text","Text"],["image","Image"],["voice","Voice message"],["video","Video thumbnail"],["sticker","GIF / sticker"],["location","Location"],["missed_call","Missed call"],["audio_call","Audio call"],["video_call","Video call"],["system","System message"]];
const reactions:[Reaction,string][]=[["","None"],["heart","❤"],["laugh","😂"],["thumbs_up","👍"],["thumbs_down","👎"],["fire","🔥"],["surprise","😮"]];
const mediaTypes=new Set(["image","video","sticker"]);

export function MessageEditor({doc,onChange}:{doc:FakeChatDocument;onChange:(doc:FakeChatDocument)=>void}){
  const [sender,setSender]=React.useState<ParticipantId>("A");const [text,setText]=React.useState("");
  const add=()=>{if(!text.trim())return;onChange({...doc,messages:[...doc.messages,newMessage(sender,text.trim())]});setText("")};
  return <section className={styles.messageEditor}><div className={styles.fastComposer}><div className={styles.senderToggle}><button className={sender==="A"?styles.on:""} onClick={()=>setSender("A")} type="button">A</button><button className={sender==="B"?styles.on:""} onClick={()=>setSender("B")} type="button">B</button></div><textarea aria-label="New text message" value={text} placeholder="Type the next message…" onChange={(e)=>setText(e.target.value)} onKeyDown={(e)=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();add()}}}/><button type="button" onClick={add}>Add</button></div>
    <button type="button" className={styles.addAdvanced} onClick={()=>onChange({...doc,messages:[...doc.messages,newMessage("A","","text")]})}>＋ Add message</button>
    <div className={styles.messageList}>{doc.messages.map((message,index)=><article className={styles.messageItem} key={message.id}><div className={styles.messageTop}><select aria-label="Sender" value={message.sender} onChange={(e)=>onChange(updateMessage(doc,{...message,sender:e.target.value as ParticipantId}))}><option value="A">Person A</option><option value="B">Person B</option></select><select aria-label="Message type" value={message.type} onChange={(e)=>onChange(updateMessage(doc,{...message,type:e.target.value as MessageType}))}>{TYPES.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><span>#{index+1}</span></div>
      {mediaTypes.has(message.type)&&<label className={styles.mediaInput}>Upload media<input type="file" accept="image/*" onChange={(e)=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>onChange(updateMessage(doc,{...message,media:String(reader.result||"")}));reader.readAsDataURL(file)}}/></label>}
      <textarea aria-label="Message content" value={message.content} placeholder={message.type==="location"?"Location title":message.type==="system"?"System event":"Message or caption"} onChange={(e)=>onChange(updateMessage(doc,{...message,content:e.target.value}))}/>
      <details><summary>Details</summary><div className={styles.detailGrid}><label>Time<input value={message.timestamp} onChange={(e)=>onChange(updateMessage(doc,{...message,timestamp:e.target.value}))}/></label><label>Duration / subtitle<input value={message.duration} onChange={(e)=>onChange(updateMessage(doc,{...message,duration:e.target.value}))}/></label><label>Reaction<select value={message.reaction} onChange={(e)=>onChange(updateMessage(doc,{...message,reaction:e.target.value as Reaction}))}>{reactions.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Reply to<select value={message.replyTo||""} onChange={(e)=>onChange(updateMessage(doc,{...message,replyTo:e.target.value||null}))}><option value="">None</option>{doc.messages.filter((item)=>item.id!==message.id).map((item,i)=><option value={item.id} key={item.id}>#{i+1} {item.content.slice(0,28)||item.type}</option>)}</select></label></div><div className={styles.checks}><label><input type="checkbox" checked={message.seen} onChange={(e)=>onChange(updateMessage(doc,{...message,seen:e.target.checked}))}/>Seen</label><label><input type="checkbox" checked={message.edited} onChange={(e)=>onChange(updateMessage(doc,{...message,edited:e.target.checked}))}/>Edited</label>{message.type==="voice"&&<label><input type="checkbox" checked={message.played} onChange={(e)=>onChange(updateMessage(doc,{...message,played:e.target.checked}))}/>Played</label>}</div></details>
      <div className={styles.messageActions}><button type="button" onClick={()=>onChange(moveMessage(doc,message.id,-1))} disabled={!index}>↑</button><button type="button" onClick={()=>onChange(moveMessage(doc,message.id,1))} disabled={index===doc.messages.length-1}>↓</button><button type="button" onClick={()=>onChange(duplicateMessage(doc,message.id))}>Duplicate</button><button type="button" className={styles.danger} onClick={()=>onChange(deleteMessage(doc,message.id))}>Delete</button></div></article>)}</div></section>
}
